openapi: 3.0.3
info:
  title: Users Service
  contact:
    name: API Support
    url: https://ensi.tech/contacts
    email: kizil@mail.com
  version: 1.0.0
  description: User Service
servers:
  - url: /
tags:
  - name: users
    description: Users
paths:
  /user/register:
    post:
      tags:
        - users
      operationId: userRegister
      x-lg-handler: 'App\Http\ApiV1\Modules\Games\Controllers\AuthController@register'
      summary: User register
      description: User register
      requestBody:
        content:
          application/json:
            schema:
              $ref: './users/users.yaml#/AuthRequest'
      responses:
        "202":
          description: Успешный ответ
        "400":
          $ref: '#/components/responses/BadRequest'
        "404":
          $ref: '#/components/responses/NotFound'
        "500":
          $ref: '#/components/responses/ServerError'
  /user/auth:
    post:
      tags:
        - users
      operationId: userLogin
      x-lg-handler: 'App\Http\ApiV1\Modules\Games\Controllers\AuthController@auth'
      summary: User login
      description: User login
      requestBody:
        content:
          application/json:
            schema:
              $ref: './users/users.yaml#/AuthRequest'
      responses:
        "200":
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: './users/users.yaml#/UserResponse'
        "400":
          $ref: "#/components/responses/BadRequest"
        "403":
          $ref: '#/components/responses/BadRequest'
        "500":
          $ref: '#/components/responses/ServerError'

components:
  parameters:
    QueryInclude:
      $ref: './common_parameters.yaml#/QueryInclude'
    PathId:
      $ref: './common_parameters.yaml#/PathId'
  schemas:
    EmptyDataResponse:
      type: object
      properties:
        data:
          type: object
          nullable: true
        meta:
          type: object
      required:
        - data
    PaginationTypeEnum:
      $ref: './common_schemas.yaml#/PaginationTypeEnum'
  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: './errors.yaml#/ErrorResponse'
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: './errors.yaml#/ErrorResponse'
    ServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: './errors.yaml#/ErrorResponse'